name: Docker Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t my-image:latest .

    - name: Run Trivy to scan the image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-image:latest
        format: 'table'
        output: /github/workspace/trivy-report.txt
        exit-code: '0'  # 将 exit-code 设置为 0，不让构建因漏洞而失败
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'HIGH,CRITICAL'

    - name: Fix file permissions
      run: |
        sudo chown runner:docker trivy-report.txt
        sudo chmod 644 trivy-report.txt

    - name: Read Trivy Report Content
      id: read_report
      run: |
        REPORT_CONTENT=$(cat trivy-report.txt)
        REPORT_CONTENT_JSON=$(echo "$REPORT_CONTENT" | jq -Rs .)
        echo "REPORT_CONTENT=$REPORT_CONTENT_JSON" >> $GITHUB_ENV

    - name: Send Trivy Report to Slack
      if: always()
      env:
        SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
        SLACK_CHANNEL: '#trivy'
        REPORT_CONTENT: ${{ env.REPORT_CONTENT }}
      run: |
        curl -X POST -H "Authorization: Bearer $SLACK_OAUTH_TOKEN" \
            -H 'Content-type: application/json' \
            --data "{
                \"channel\":\"$SLACK_CHANNEL\",
                \"text\":\"Here is the Trivy scan report:\n$REPORT_CONTENT\"
            }" \
            https://slack.com/api/chat.postMessage




