name: Docker Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t my-image:latest .

    - name: Run Trivy to scan the image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-image:latest
        format: 'table'
        exit-code: '0'  # 将 exit-code 设置为 0，不让构建因漏洞而失败
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'HIGH,CRITICAL'

    - name: Upload Trivy scan results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: trivy-report.txt

    - name: Send Slack Notification
      if: always()  # 无论成功还是失败都会发送通知
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        MESSAGE="*GitHub Actions Workflow Completed*"
        STATUS="*Status*: ${{ job.status }}"
        URL="*Workflow URL*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

        if [ "${{ job.status }}" == "success" ]; then
          COLOR="#36a64f"
        else
          COLOR="#ff0000"
        fi

        curl -X POST -H 'Content-type: application/json' --data "{
          \"attachments\": [
            {
              \"color\": \"$COLOR\",
              \"pretext\": \"GitHub Actions Notification\",
              \"title\": \"$MESSAGE\",
              \"fields\": [
                { \"title\": \"Status\", \"value\": \"$STATUS\", \"short\": true },
                { \"title\": \"Workflow URL\", \"value\": \"$URL\", \"short\": false }
              ]
            }
          ]
        }" $SLACK_WEBHOOK_URL
