name: Docker Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for building the Docker image
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t my-image:latest .

  # Job for running Trivy scan
  trivy-scan:
    runs-on: ubuntu-latest
    needs: build # This ensures the image is built before this job runs
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy to scan the image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-image:latest
        format: 'table'
        output: /github/workspace/trivy-report.txt
        exit-code: '0'  # Don't fail immediately, let the report be processed
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'HIGH, CRITICAL'

    - name: Upload Trivy Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: trivy-report.txt

    - name: Send Artifact Link to Slack
      if: always()
      env:
        SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
        SLACK_CHANNEL: '#trivy'
      run: |
        RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        curl -X POST -H "Authorization: Bearer $SLACK_OAUTH_TOKEN" \
            -H 'Content-type: application/json' \
            --data "{
                \"channel\":\"$SLACK_CHANNEL\",
                \"text\":\"The Trivy scan has completed. You can download the full report from the GitHub Actions artifacts: $RUN_URL\"
            }" \
            https://slack.com/api/chat.postMessage
    
    # Check for vulnerabilities and fail if CRITICAL ones are found
    - name: Check for Critical Vulnerabilities in Trivy Report
      run: |
        if grep "CRITICAL" /github/workspace/trivy-report.txt; then
          echo "Critical vulnerabilities found!" >&2
          exit 1
        fi

  # Job for running Docker Bench Security scan
  dockerbench-scan:
    runs-on: ubuntu-latest
    needs: build # This ensures the image is built before this job runs
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Docker Bench Security
      run: |
        docker run --net host --pid host --userns host --cap-add audit_control \
        -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
        -v /var/lib:/var/lib \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /usr/lib/systemd:/usr/lib/systemd \
        -v /etc:/etc \
        --label docker_bench_security \
        docker/docker-bench-security > dockerbench-report.txt

    - name: Upload Docker Bench scan results
      uses: actions/upload-artifact@v3
      with:
        name: dockerbench-report
        path: dockerbench-report.txt

    - name: Upload Docker Bench Report to Slack
      if: always()
      env:
        SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
        SLACK_CHANNEL: '#dockerbench'
      run: |
        curl -F file=@dockerbench-report.txt \
              -F "initial_comment=Here is the Docker Bench security report." \
              -F channels=$SLACK_CHANNEL \
              -H "Authorization: Bearer $SLACK_OAUTH_TOKEN" \
              https://slack.com/api/files.upload
    
    # Fail if any high-risk findings in Docker Bench report
    - name: Fail if high security risks are found in Docker Bench report
      run: |
        if grep -E "Ensure only needed ports are open on the container" dockerbench-report.txt; then
          echo "Security risks found in Docker Bench report" >&2
          exit 1
        fi