name: Docker Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t my-image:latest .

    - name: Run Trivy to scan the image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-image:latest
        format: 'table'
        output: /github/workspace/trivy-report.txt
        exit-code: '0'  # 将 exit-code 设置为 0，不让构建因漏洞而失败
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'HIGH,CRITICAL'

    - name: Upload Trivy scan results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: trivy-report.txt
    - name: Print working directory and list files
      run: |
        echo "Current directory:"
        pwd
        echo "Files in current directory:"
        ls -al


    - name: Get Slack Upload URL
      if: always()
      env:
        SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
      run: |
        RESPONSE=$(curl -s -X POST -H "Authorization: Bearer $SLACK_OAUTH_TOKEN" \
          --data "filename=trivy-report.txt&length=$(stat --format=%s trivy-report.txt)" \
          https://slack.com/api/files.getUploadURLExternal)
        echo $RESPONSE
        UPLOAD_URL=$(echo $RESPONSE | jq -r '.upload_url')
        FILE_ID=$(echo $RESPONSE | jq -r '.file_id')
        echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV
        echo "FILE_ID=$FILE_ID" >> $GITHUB_ENV


    - name: Upload File to Slack
      if: always()
      env:
        UPLOAD_URL: ${{ env.UPLOAD_URL }}
      run: |
        curl -X POST \
          -F filename=@trivy-report.txt \
          $UPLOAD_URL


    - name: Complete Slack Upload
      if: always()
      env:
        SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
        FILE_ID: ${{ env.FILE_ID }}
      run: |
        curl -X POST -H "Authorization: Bearer $SLACK_OAUTH_TOKEN" \
          --data-urlencode "file_id=$FILE_ID" \
          --data-urlencode "files[0][id]=$FILE_ID" \
          --data-urlencode "files[0][title]=Trivy Scan Report" \
          https://slack.com/api/files.completeUploadExternal


    - name: Send Slack Message with File
      if: always()
      env:
        SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
        SLACK_CHANNEL: '#trivy'
        FILE_ID: ${{ env.FILE_ID }}
      run: |
        curl -X POST -H "Authorization: Bearer $SLACK_OAUTH_TOKEN" \
            -H 'Content-type: application/json' \
            --data "{
                \"channel\":\"$SLACK_CHANNEL\",
                \"text\":\"Here is the Trivy scan report for the latest build.\",
                \"attachments\": [
                    {
                        \"text\": \"Click to view the report\",
                        \"fallback\": \"View the report\",
                        \"actions\": [
                            {
                                \"type\": \"button\",
                                \"text\": \"View Report\",
                                \"url\": \"https://slack.com/files/$FILE_ID\"
                            }
                        ]
                    }
                ]
            }" \
            https://slack.com/api/chat.postMessage



